
package clases;

import java.awt.event.KeyEvent;
import javax.swing.WindowConstants;
import main.Menu;
import mySqlConn.MySqlConn;


public class Comprobante extends javax.swing.JFrame {
    
    MySqlConn conn;
    String nombre, ciudad,Date,Date2,tipoHab;
    int numHab,piso,totalPersonas;
    
    
    public Comprobante(MySqlConn conn,String nombre,String ciudad,String Date,String Date2,int numHab,int piso,String tipoHab,int totalPersonas){
        this.conn = conn;
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.Date = Date;
        this.Date2 = Date2;
        this.tipoHab = tipoHab;
        this.numHab = numHab;
        this.piso = piso;
        this.totalPersonas = totalPersonas;
        initComponents();
        
        this.jLabelSeleccionar1.setVisible(false);
        this.jLabelSeleccionar2.setVisible(false);
        
        colocarDatos();
        
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }
    
    public Comprobante() {
        initComponents();
    }
    
    private void colocarDatos(){
        this.jLabelNombre.setText(nombre);
        this.jLabelCiudad.setText(ciudad);
        this.jLabelFechaIng.setText(Date);
        this.jLabelFechaSal.setText(Date2);
        
        String numH = String.valueOf(numHab);
        this.jLabelNumHab.setText(numH);
        
        String Piso = String.valueOf(piso);
        this.jLabelPiso.setText(Piso);
        
        this.jLabelTipoHab.setText(tipoHab);
        
        int lim = obtenerLimite();
        String Limite = String.valueOf(lim);
        this.jLabelLimitePer.setText(Limite);
        
        String totalPer = String.valueOf(totalPersonas);
        this.jLabelTotalOcPer.setText(totalPer);
        
        int extras = personasExtras();
        if(extras == 0){
            this.jLabelSeleccionar1.setVisible(false);
            this.jLabelSeleccionar2.setVisible(false);
        }else if(extras == 1){
            this.jLabelSeleccionar1.setVisible(true);
            this.jLabelSeleccionar2.setVisible(false);
        }else if(extras == 2){
            this.jLabelSeleccionar1.setVisible(false);
            this.jLabelSeleccionar2.setVisible(true);
        }
    }
    
    private int personasExtras(){
        int extras=0;
        switch (this.tipoHab) {
            case "Sencilla":
                extras = (totalPersonas - 1);break;
            case "Doble":
                extras = (totalPersonas - 2);break;
            case "Triple":
                extras = (totalPersonas - 3);break;
        }
        return extras;
    }
    
    private int obtenerLimite(){
        int limite = 0;
        switch (this.tipoHab) {
            case "Sencilla":
                limite = 1;break;
            case "Doble":
                limite = 2;break;
            case "Triple":
                limite = 3;break;
        }
        return limite;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelFechaIng = new javax.swing.JLabel();
        jLabelFechaSal = new javax.swing.JLabel();
        jLabelNumHab = new javax.swing.JLabel();
        jLabelPiso = new javax.swing.JLabel();
        jLabelTipoHab = new javax.swing.JLabel();
        jLabelLimitePer = new javax.swing.JLabel();
        jLabelTotalOcPer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelSeleccionar2 = new javax.swing.JLabel();
        jLabelSeleccionar1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Comprabante de Registro"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logoc.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 50));

        jLabelNombre.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 210, 20));

        jLabelCiudad.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 210, 20));

        jLabelFechaIng.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelFechaIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 210, 20));

        jLabelFechaSal.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelFechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 210, 20));

        jLabelNumHab.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelNumHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 60, 20));

        jLabelPiso.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 60, 20));

        jLabelTipoHab.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 20));

        jLabelLimitePer.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelLimitePer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 30, 20));

        jLabelTotalOcPer.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        getContentPane().add(jLabelTotalOcPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 60, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("Hotel Montrial");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("\"Los mejores recuerdos empiezan aquí\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Av. Bonampak Sm. 10 Mza. 2 Lote 7, Cancún,");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Quintana Roo. México");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Huésped:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Ciudad Origen:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Fecha de Ingreso:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Fecha de Salida:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("No. Habitación:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("Piso:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel12.setText("Tipo de Habitación:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel13.setText("(Límite");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel14.setText("húesped)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel15.setText("Total de ocupantes de la Habitación:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel16.setText("1 Persona Extra");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel17.setText("2 Personas Extras");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel18.setText("¡Registro Completado!");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        jLabelSeleccionar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Seleccionar.png"))); // NOI18N
        getContentPane().add(jLabelSeleccionar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 20, 20));

        jLabelSeleccionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Seleccionar.png"))); // NOI18N
        getContentPane().add(jLabelSeleccionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 20, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Comprobante.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprobante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelFechaIng;
    private javax.swing.JLabel jLabelFechaSal;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLimitePer;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumHab;
    private javax.swing.JLabel jLabelPiso;
    private javax.swing.JLabel jLabelSeleccionar1;
    private javax.swing.JLabel jLabelSeleccionar2;
    private javax.swing.JLabel jLabelTipoHab;
    private javax.swing.JLabel jLabelTotalOcPer;
    // End of variables declaration//GEN-END:variables
}
